### ISSUE TITLE
Breeding pool

### ISSUE THREAD

**Issue by mtg-toolz** [Haven-King/Proximity#21]
Not sure what is causing it to fail as the only error that spits out is index 38, length 38. 

To re-create issue, download latest ver and add 1x Breeding Pool to text file or use one of your test text that has it. The one with  the following will start with breeding pool and fail then it will download 3 of the 5, giving no fail or saved message for Rhox Bodyguard. 

1x Elbrus, the Binding Blade // Withengar Unbound
1x Breeding Pool
1x Rhox Bodyguard
1x Sovereigns of Lost Alara
1x Slippery Bogle

**Comment by Haven-King** [comment]
Fixed in 0.3.2
