### ISSUE TITLE
SVG processing error

### ISSUE THREAD

**Issue by yaceek** [Haven-King/Proximity#25]
When trying out set SVG set symbols from CCGHQ forums (https://www.slightlymagic.net/forum/viewtopic.php?f=15&t=7010) I encountered an NPE during processing (SVGLayerRendered.java, line 53). This is due to SVG files missing viewbox attribute in the svg element, only width/height attributes are present as seen in the sample: [R.svg.txt](https://github.com/Haven-King/Proximity/files/7257651/R.svg.txt).

Current code for this looks like this:
```java
SVGRect svgBounds = root.getViewBox().getBaseVal();
double svgWidth = svgBounds.getWidth(), svgHeight = svgBounds.getHeight();
````

Unfortunately the batik API doesn't have a simple way of checking if the viewbox attribute is available, so a simple workaround I'm using right now uses this:
```java
double svgWidth, svgHeight;
SVGRect svgBounds = root.getViewBox().getBaseVal();
try {
  svgWidth = svgBounds.getWidth();
  svgHeight = svgBounds.getHeight();
}
catch (Exception ex) {
    svgWidth = root.getWidth().getBaseVal().getValue();
    svgHeight = root.getHeight().getBaseVal().getValue();
    svgBounds.setX(0);
    svgBounds.setY(0);
    svgBounds.setWidth((float)svgWidth);
    svgBounds.setHeight((float)svgHeight);
}
```

But I suppose it can be made even better...

**Comment by yaceek** [comment]
I also observed additional problem with scaling/positioning when the svg has x/y/width/height values with pt/mm units instead of pixels.

**Comment by Haven-King** [comment]
The way set symbols work right now are very particular to allow for some shortcuts (notably, only having one set symbol SVG, instead of one for each rarity). A better system might be possible, but once I document what I'm doing I think it will be better for them to use a unified format than to try and make every possible variation of SVG (of which there are a lot) to work.

**Comment by yaceek** [comment]
Sure, I don't have a problem with the way set symbols are implemented in the template, just with the technicalities inside svg files that might pose a problem, which of course can be easily solved editing the xml ;)

Although in a couple cases the current generation of the gradient is wrong... for example CRM, MH2 (and maybe other sets) uses vertical and not diagonal gradient :)
