### ISSUE TITLE
Missing color indicator for transforming DFCs, redundant p/t

### ISSUE THREAD

**Issue by malgox** [Haven-King/Proximity#27]
Really minor issue, but the render for the backside of transforming double-faced cards is missing the colored circle by the typeline that indicates the card's color. See Avacyn the Purifier as an example. Also, the backside of TDFCs include the front side's power/toughness, which is wrong. Only the front of a TDFC includes reminder power/toughness for the back. Not the other way around.

**Comment by Haven-King** [comment]
Fixed in https://github.com/Haven-King/Proximity/commit/d7b51e6a0ba1a269498aeafd878fec899c35a645
