### ISSUE TITLE
Consider allowing older versions of java to run the pre-built jars

### ISSUE THREAD

**Issue by alexander-novo** [Haven-King/Proximity#32]
Both versions of java I have installed on my machine (`OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)` and `Java(TM) SE Runtime Environment (build 1.8.0_251-b08)`) were built in 2020 and yet neither of them is even close to being able to run the jars built on the release page. I bet most other people's versions of Java are even older.

When I try and run it, I get this:
```
Error: LinkageError occurred while loading main class dev.hephaestus.proximity.Main
        java.lang.UnsupportedClassVersionError: dev/hephaestus/proximity/Main has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

**Comment by Haven-King** [comment]
The [How To page on the wiki](https://github.com/Haven-King/Proximity/wiki/How-to-Use#getting-started) specifies that Java 16+ is required. For Proximity to function on earlier versions of Java, portions of it would need to be rewritten, and this isn't something I am interested in doing anytime soon.
