### ISSUE TITLE
Artist Name font is wrong and size is to big

### ISSUE THREAD

**Issue by joshuabengal** [Haven-King/Proximity#9]
Compared a Proximity render to other existing scans in Photoshop and the Artist Name font is off and the size is too big by what looks to be about 2 points. 

Top line is Proximity, bottom one is existing card scan
![Untitled-2](https://user-images.githubusercontent.com/13399585/134034070-2166cdf4-346f-4bdd-8aeb-321b15e5afb6.jpg)

**Comment by AnthonyJiangTang** [comment]
https://github.com/AnthonyJiangTang/Proximity
